######################################
#描述：部署redis集群
#作者：wangzhenqii@cecdat.con
#时间：2020年04月16日
#版权：中电（福建）健康医疗大数据运营服务有限公司
######################################
---
- hosts: ambari_server:ambari_agent 
  roles:
    - {role: ambari_uninstall}
  tags:
    - ambari_uninstll
    
- hosts: mariadb_ambari
  roles:
    - {role: ambari_mariadb}
  tags:
    - ambari_mariadb

- hosts: ambari_agent
  roles:
    - {role: ambari_agent}
  tags:
    - ambari_agent
    
- hosts: ambari_server
  roles:
    - {role: ambari_server}
  tags:
    - ambari_server
