######################################
#描述：部署keepalived主从
#作者：wangzhenqi@cecdat.com
#时间：2020年04月16日
#版权：中电（福建）健康医疗大数据运营服务有限公司
######################################

---
- hosts: harbor
  roles:
    - {role: pexpect}
  tags:
    - pexpect
    
- hosts: harbor 
  roles:
    - {role: harbor}
  tags:
    - harbor
