######################################
#描述：部署keepalived主从
#作者：wangzhenqi@cecdat.com
#时间：2020年04月16日
#版权：中电（福建）健康医疗大数据运营服务有限公司
######################################

---
- hosts: k8s_master:k8s_work
  roles:
    - {role: k8s_init}
  tags:
    - k8s_init
- hosts: k8s_master:k8s_work
  roles:
    - {role: pexpect}
  tags:
    - pexpect
- hosts: master01 
  roles:
    - {role: k8s_master01}
  tags:
    - k8s_master01
- hosts: master01 
  roles:
    - {role: k8s_join}
  tags:
    - k8s_join
- hosts: master02
  roles:
    - {role: k8s_master02}
  tags:
    - k8s_master02
- hosts: master03
  roles:
    - {role: k8s_master03}
  tags:
    - k8s_master03
- hosts: k8s_work
  roles:
    - {role: k8s_work}
  tags:
    - k8s_work
    
- hosts: master01
  roles:
    - {role: k8s_down_vip}
  tags:
    - k8s_down_vip
    
- hosts: keepalived_slave
  roles:
    - {role: keepalived_slave}
  tags:
    - keepalived_slave
    
- hosts: keepalived_master
  roles:
    - {role: keepalived_master}
  tags:
    - keepalived_master

- hosts: k8s_master
  roles:
    - {role: k8s_realserver}
  tags:
    - k8s_realserver
