######################################
#描述：部署keepalived主从
#作者：wangzhenqi@cecdat.com
#时间：2020年04月16日
#版权：中电（福建）健康医疗大数据运营服务有限公司
######################################

---
- hosts: k8s_client 
  roles:
    - {role: k8s_ingress}
  tags:
    - k8s_ingress
