######################################
#描述：部署redis集群
#作者：wangzhenqii@cecdat.con
#时间：2020年04月16日
#版权：中电（福建）健康医疗大数据运营服务有限公司
######################################
---
- hosts: mariadb 
  roles:
    - {role: pexpect}
  tags:
    - pexpect 
    
- hosts: mariadb 
  roles:
    - {role: mariadb}
  tags:
    - mariadb

- hosts: mariadb 
  roles:
    - {role: pymysql}
  tags:
    - pymysql
