######################################
#描述：部署nginx
#作者：wangzhenqi@cecdat.com
#时间：2020年04月16日
#版权：中电（福建）健康医疗大数据运营服务有限公司
######################################
---
- hosts: nginx 
  roles:
    - role: nginx
  tags:
  - nginx    
