######################################
#描述：部署pg主从流复制及单点部署
#作者：wangzhenqii@cecdat.con
#时间：2020年04月16日
#版权：中电（福建）健康医疗大数据运营服务有限公司
######################################
---
- hosts: postgres_master #master服务器部署pg
  roles:
    - {role: pg_master}
  tags:
    - pg_master
- hosts: postgres_slave #slave服务器部署pg
  roles:
    - {role: pg_slave}
  tags:
    - pg_slave
- hosts: postgres_master #master上验证HA
  roles:
    - {role: pg_ha}
  tags:
    - pg_ha
  
- hosts: postgres_single #服务器上部署单点pg
  roles:
    - {role: pg_single}
  tags:
    - pg_single


