######################################
#描述：部署统一门户
#作者：wangzhenqii@cecdat.con
#时间：2020年04月16日
#版权：中电（福建）健康医疗大数据运营服务有限公司
######################################
---
- hosts: postgres_master
  roles:
    - {role: portal_pg}
  tags:
    - portal_pg
- hosts: portal_web
  roles:
    - {role: portal_web}
  tags:
    - portal_web
- hosts: portal_web
  roles:
    - {role: portal_web_update}
  tags:
    - portal_web_update
- hosts: portal_app
  roles:
    - {role: portal_app}
  tags:
    - portal_app
- hosts: portal_app
  roles:
    - {role: portal_app_update}
  tags:
    - portal_app_update
