######################################
#描述：部署redis集群		
#作者：wangzhenqi@cecdat.com
#时间：2020年04月16日
#版权：中电（福建）健康医疗大数据运营服务有限公司
######################################
---

- hosts: redis02  
#  gather_facts: no
  roles:
    - {role: redis02}
  tags:
    - redis02
- hosts: redis03  
#  gather_facts: no
  roles:
    - {role: redis03}
  tags:
    - redis03

- hosts: redis01  
#  gather_facts: no
  roles:
    - {role: redis01}
  tags:
    - redis01
    
